[workspace]
release = false
release_always = false
publish_timeout = "10m"

[[package]]
name = "mnesis-bombay-core"
release = true

[[package]]
name = "mnesis-bombay"
release = true

[[package]]
name = "mnesis-bombay-tower"
release = true
